server:
  port: 8066
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus: debug
exa:
  get-item-url: ${exa.host}/exawebapi/exaitem/getitems